include_recipe "symfony::update"
include_recipe "symfony::apache"
include_recipe "symfony::php"
include_recipe "git"
include_recipe "mysql::server"
include_recipe "java"
include_recipe "symfony::cleanup"
