maintainer        "Roderik van der Veer"
maintainer_email  "roderik@vanderveer.be"
license           "Apache 2.0"
description       ""
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           "1.0"
supports          "ubuntu"

depends "apache2"
depends "git"
depends "php"
depends "composer"
depends "symfony2"
depends "mysql"
depends "java"
